import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {Store,hash} from '../src/store.js';
import {createApp} from '../src/server.js';
import {normalizeUsage,DemoProvider} from '../src/providers.js';
import {modelPolicyViolation} from '../src/model-policy.js';
import {centerAnsi,extractSgrMouseEvents,stripAnsi,visibleLength} from '../src/terminal-layout.js';
import {buildShowcaseReel,showcaseWeight,shuffleModels} from '../src/reel.js';
const configuration=()=>({dataDir:':memory:',provider:'demo',accessCode:'test-secret',testers:['one@test.local','two@test.local'],admins:['one@test.local'],origin:'http://localhost:3131',secureCookie:false,liveEnabled:false,dailyUsd:5,maxOutput:1024,maxInputBytes:24000});
function setup(overrides={}){const cfg={...configuration(),...overrides};return {cfg,store:new Store(':memory:',cfg)};}
async function server(t,options={}){const {cfg,store}=setup(options.cfg);const {app,reconcile}=createApp(cfg,{store,provider:options.provider});const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));const url=`http://127.0.0.1:${s.address().port}`;t.after(()=>{s.closeAllConnections();s.close();store.close();});const call=async(route,body,key,extra={})=>{const r=await fetch(url+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(key?{Authorization:`Bearer ${key}`}:{ }),...extra.headers},body:body?JSON.stringify(body):undefined,...extra});let data;try{data=await r.json();}catch{}return {status:r.status,data,headers:r.headers};};const login=async(email='one@test.local')=>(await call('/auth/login',{email,code:'test-secret',cli:true})).data.key;return {cfg,store,url,call,login,reconcile};}

test('24-model collection has exact tier boundaries, immutable snapshots, and replay safety',()=>{const {store}=setup();const u=store.user('one@test.local'),pool=store.pool();assert.equal(pool.entries.length,24);assert.equal(new Set(pool.entries.map(e=>e.model)).size,24);assert.equal(pool.entries.reduce((n,e)=>n+e.weight,0),10000);const a=store.spin(u,'one',()=>0);assert.equal(a.award.choice.tier,'bust');assert.equal(a.award.total,1000000);assert.equal(store.spin(u,'one',()=>9999).award.id,a.award.id);assert.equal(store.spin(u,'two',()=>3000).award.choice.tier,'common');assert.equal(store.spin(u,'three',()=>6500).award.choice.tier,'rare');assert.equal(store.spin(u,'four',()=>8500).award.choice.tier,'epic');assert.equal(store.spin(u,'five',()=>9500).award.choice.tier,'legendary');assert.equal(store.spin(u,'six',()=>9900).award.choice.tier,'mythic');const changed=pool.entries.map(e=>({...e,name:e.name+' v2'}));store.publishPool(changed,u.id);assert.equal(store.award(u,a.award.id).choice.name,'Llama 3.2 1B');assert.notEqual(store.pool().version,a.award.pool_version);store.close();});

test('canonical Bust and Rare tiers contain no coding-focused Rare models',()=>{const {store}=setup(),entries=store.pool().entries;assert.deepEqual([...new Set(entries.map(entry=>entry.tier))],['bust','common','rare','epic','legendary','mythic']);const rare=entries.filter(entry=>entry.tier==='rare');assert.equal(rare.length,6);assert.equal(rare.some(entry=>/(coder|codestral|devstral|\bcode\b)/i.test(entry.name+' '+entry.model)),false);store.close();});

test('pool policy permits the named collection but rejects lookalike identities',()=>{const {store}=setup(),base=store.pool().entries[0];const entry=(id,name,model)=>[{...base,id,name,model,weight:100}];for(const [id,name,model] of [['sonnet','Claude Sonnet 5','anthropic/claude-sonnet-5'],['opus','Claude Opus 5.5','anthropic/claude-opus-5.5'],['sol','GPT-6 Sol','openai/gpt-6-sol'],['astra','GPT-6 Astra','openai/gpt-6-astra'],['oss','gpt-oss-20b','openai/gpt-oss-20b']])assert.doesNotThrow(()=>store.publishPool(entry(id,name,model),'test'));for(const [id,name,model] of [['old-sonnet','Claude Sonnet 4','anthropic/claude-sonnet-4'],['mini','Codex Mini','openai/codex-mini'],['hidden-sonnet','Claude Opus 5.5','anthropic/claude-sonnet-4'],['hidden-mini','GPT-6 Astra','openai/codex-mini']])assert.throws(()=>store.publishPool(entry(id,name,model),'test'),error=>error.code==='model_policy');store.close();});

test('startup retires a legacy active pool below the model floor',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootlm-policy-'));try{const cfg=configuration(),file=path.join(dir,'db.sqlite');let store=new Store(file,cfg);const legacy=[{...store.pool().entries[0],id:'sonnet',name:'Claude Sonnet 4',model:'anthropic/claude-sonnet-4'}];store.db.prepare('INSERT INTO pools(version,body,created_at) VALUES(?,?,?)').run('pool_legacy',JSON.stringify(legacy),new Date().toISOString());store.set('pool_demo','pool_legacy');store.close();store=new Store(file,cfg);assert.notEqual(store.pool().version,'pool_legacy');assert.equal(store.pool().entries.some(modelPolicyViolation),false);store.close();}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('reservations prevent overspending and settlement is exactly once',()=>{const {store}=setup();const u=store.user('a');const a=store.spin(u,'spin',()=>10).award;const r=store.reserve(u,a.id,'first','fp',800000,0).request;assert.throws(()=>store.reserve(u,a.id,'second','fp2',300000,0),e=>e.code==='insufficient_tokens');assert.equal(store.award(u,a.id).reserved,800000);store.settle(r.id,{input:100,output:200,cost:0});store.settle(r.id,{input:100,output:200,cost:0});assert.equal(store.award(u,a.id).remaining,999700);assert.equal(store.award(u,a.id).reserved,0);assert.equal(store.reserve(u,a.id,'first','fp',800000,0).prior.id,r.id);assert.throws(()=>store.reserve(u,a.id,'first','different',1,0),e=>e.code==='idempotency_conflict');store.close();});

test('user isolation, key hashing and revocation',()=>{const {store}=setup();const u=store.user('a'),v=store.user('b');const a=store.spin(u,'spin',()=>10).award;assert.throws(()=>store.award(v,a.id),e=>e.status===404);const k=store.credential(u);assert.equal(store.authenticate(k.key).id,u.id);assert.equal(store.db.prepare('SELECT hash FROM credentials WHERE id=?').get(k.id).hash,hash(k.key));assert.equal(store.keys(v).length,0);assert.equal(store.revoke(v,k.id),0);store.revoke(u,k.id);assert.equal(store.authenticate(k.key),null);store.close();});

test('daily cap includes active reservations; rejection releases once',()=>{const {store}=setup({dailyUsd:1});const u=store.user('a');const a=store.spin(u,'spin',()=>10).award;const r=store.reserve(u,a.id,'r','fp',100,.8).request;assert.throws(()=>store.reserve(u,a.id,'s','fp2',100,.3),e=>e.code==='daily_budget');store.release(r.id,'rejected');store.release(r.id,'rejected');assert.equal(store.award(u,a.id).reserved,0);assert.ok(store.reserve(u,a.id,'s','fp2',100,.9).request);store.close();});

test('uncertain requests remain reserved after recovery; unexpected costs pause inference',()=>{const {store}=setup();const u=store.user('a');const a=store.spin(u,'s',()=>10).award;const r=store.reserve(u,a.id,'r','f',100,.01).request;store.recover();assert.equal(store.request(r.id).status,'pending');assert.equal(store.award(u,a.id).reserved,100);store.settle(r.id,{input:80,output:30,cost:.02});assert.equal(store.setting('inferenceEnabled'),'false');assert.equal(store.award(u,a.id).remaining,999900);assert.equal(store.request(r.id).overage_tokens,10);assert.equal(store.stats().audit[0].action,'reservation.exceeded');store.close();});

test('usage does not double count cached or reasoning tokens',()=>{assert.deepEqual(normalizeUsage({prompt_tokens:100,completion_tokens:60,prompt_tokens_details:{cached_tokens:90},completion_tokens_details:{reasoning_tokens:40},cost:.02},{inputPrice:1,outputPrice:2}),{input:100,output:60,cost:.02});assert.throws(()=>normalizeUsage({prompt_tokens:null,completion_tokens:1},{}));});

test('API authentication, CSRF, session cookie and admin isolation',async t=>{const s=await server(t);assert.equal((await s.call('/v1/models')).status,401);assert.equal((await s.call('/auth/login',{email:'not@test.local',code:'test-secret'})).status,401);const login=await s.call('/auth/login',{email:'one@test.local',code:'test-secret'});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.equal((await s.call('/internal/me',null,null,{headers:{Cookie:cookie.split(';')[0]}})).status,200);const key=await s.login();const csrf=await fetch(s.url+'/internal/spins',{method:'POST',headers:{Authorization:`Bearer ${key}`,Origin:'https://evil.example','Content-Type':'application/json','Idempotency-Key':'x'},body:'{}'});assert.equal(csrf.status,403);const second=await s.login('two@test.local');assert.equal((await s.call('/internal/admin',null,second)).status,403);});

test('browser root is not a LootLM product surface',async t=>{const s=await server(t);const response=await fetch(s.url+'/');assert.equal(response.status,404);assert.deepEqual(await response.json(),{error:{code:'not_found',message:'LootLM is a terminal-only product. Run `loot help`.'}});});

test('end-to-end roll, chat, streaming, tools and balance',async t=>{const s=await server(t);const key=await s.login();let spin=await fetch(s.url+'/internal/spins',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':'s'},body:'{}'});assert.equal(spin.status,200);const {award}=await spin.json();const body={model:award.id,messages:[{role:'user',content:'hello'}],max_tokens:128};const chat=await s.call('/v1/chat/completions',body,key);assert.equal(chat.status,200);assert.equal(chat.data.model,award.id);assert.match(chat.data.choices[0].message.content,/demo/);const spent=chat.data.usage.total_tokens;assert.equal((await s.call('/v1/allowances',null,key)).data.data[0].remaining,1000000-spent);
 const stream=await fetch(s.url+'/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({...body,stream:true})});assert.equal(stream.status,200);assert.match(stream.headers.get('content-type'),/event-stream/);const text=await stream.text();assert.match(text,/data: \[DONE\]/);assert.match(text,/prompt_tokens/);
 const tools=await s.call('/v1/chat/completions',{...body,tools:[{type:'function',function:{name:'weather',parameters:{type:'object',properties:{}}}}],tool_choice:'required'},key);assert.equal(tools.status,200);assert.equal(tools.data.choices[0].message.tool_calls[0].function.name,'weather');assert.equal((await s.call('/v1/usage',null,key)).data.data.length,3);
 const k2=await s.login('two@test.local');assert.equal((await s.call('/v1/chat/completions',body,k2)).status,404);
});

test('inference idempotency rejects repeats without a second provider call',async t=>{const s=await server(t);const key=await s.login();const u=s.store.authenticate(key),a=s.store.spin(u,'s',()=>10).award;const body={model:a.id,messages:[{role:'user',content:'hello'}],max_tokens:20};const invoke=()=>fetch(s.url+'/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':'same'},body:JSON.stringify(body)});assert.equal((await invoke()).status,200);assert.equal((await invoke()).status,409);assert.equal(s.store.usage(u).length,1);});

test('unsupported parameters, context bounds and output limits fail before reservation',async t=>{const s=await server(t);const k=await s.login();const u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;const b={model:a.id,messages:[{role:'user',content:'hello'}],max_tokens:10};for(const body of [{...b,response_format:{}},{...b,max_tokens:2000},{...b,messages:[{role:'user',content:'x'.repeat(25000)}]},{...b,messages:[{role:'user',content:[{type:'image_url'}]}]}])assert.equal((await s.call('/v1/chat/completions',body,k)).status,400);assert.equal(s.store.usage(u).length,0);});

test('in-flight concurrent calls cannot exceed per-user limit',async t=>{let unblock;const gate=new Promise(r=>unblock=r);const demo=new DemoProvider();const provider={async generate(...args){await gate;return demo.generate(...args);},async reconcile(){return null;}};const s=await server(t,{provider});const k=await s.login(),u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;const b={model:a.id,messages:[{role:'user',content:'hi'}],max_tokens:10};const calls=[s.call('/v1/chat/completions',b,k),s.call('/v1/chat/completions',b,k)];for(let i=0;i<100&&s.store.usage(u).length<2;i++)await new Promise(r=>setTimeout(r,5));const third=await s.call('/v1/chat/completions',b,k);assert.equal(third.status,429);unblock();for(const result of await Promise.all(calls))assert.equal(result.status,200);assert.equal(s.store.award(u,a.id).reserved,0);});

test('transport failure retains reservation and reconciliation settles exactly once',async t=>{const provider={async generate(_b,_c,{onId}){onId('generation_test');throw Error('Connection lost');},async reconcile(){return {input:12,output:9,cost:0};}};const s=await server(t,{provider});const k=await s.login(),u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;const r=await s.call('/v1/chat/completions',{model:a.id,messages:[{role:'user',content:'hi'}],max_tokens:20},k);assert.equal(r.status,502);assert.ok(s.store.award(u,a.id).reserved>0);assert.equal(s.store.usage(u)[0].status,'pending');await s.reconcile();await s.reconcile();assert.equal(s.store.award(u,a.id).reserved,0);assert.equal(s.store.award(u,a.id).remaining,999979);});

test('live provider is blocked without explicit enablement',async t=>{const s=await server(t,{cfg:{provider:'openrouter'},provider:{generate(){throw Error('must not call');}}});const k=await s.login(),u=s.store.authenticate(k);s.cfg.provider='demo';const a=s.store.spin(u,'s',()=>10).award;s.cfg.provider='openrouter';assert.equal((await s.call('/v1/chat/completions',{model:a.id,messages:[{role:'user',content:'hi'}]},k)).status,503);assert.equal(s.store.usage(u).length,0);});

test('SQLite data survives reopening',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootlm-'));try{const cfg=configuration(),file=path.join(dir,'db.sqlite');let store=new Store(file,cfg);const u=store.user('a'),a=store.spin(u,'s',()=>10).award;store.close();store=new Store(file,cfg);assert.equal(store.award(u,a.id).remaining,1000000);assert.equal(store.spin(u,'s').award.id,a.id);store.close();}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('CLI help is consolidated around cards and keeps config output safe',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootlm-cli-'));try{const env={...process.env,LOOTLM_CONFIG_DIR:dir};const result=spawnSync(process.execPath,['src/cli.js','help'],{encoding:'utf8',env});assert.equal(result.status,0);assert.match(result.stdout,/loot roll/);assert.match(result.stdout,/loot collection/);assert.match(result.stdout,/MODEL CASINO/);assert.doesNotMatch(result.stdout,/loot preview/);fs.writeFileSync(path.join(dir,'config.json'),JSON.stringify({key:'secret-value',url:'http://localhost:3131'}));const conf=spawnSync(process.execPath,['src/cli.js','config'],{encoding:'utf8',env});assert.equal(conf.status,0);assert.doesNotMatch(conf.stdout,/secret-value/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('redundant odds and preview commands are removed',()=>{for(const command of ['odds','preview']){const result=spawnSync(process.execPath,['src/cli.js',command],{encoding:'utf8'});assert.equal(result.status,1);assert.match(result.stderr,/Unknown command/);}});

test('ANSI color never changes terminal alignment',()=>{const plain='|  [A6] GPT-6 ASTRA                                      MYTHIC  |',colored='\x1b[36m|\x1b[0m\x1b[1;31m  [A6] GPT-6 ASTRA                                      MYTHIC  \x1b[0m\x1b[36m|\x1b[0m';assert.equal(stripAnsi(centerAnsi(colored,110)),centerAnsi(plain,110));assert.equal(visibleLength(colored),plain.length);});

test('complete mouse drags are consumed without leaking release bytes',()=>{const input='\x1b[<0;94;6M\x1b[<32;94;9M\x1b[<0;94;11m';const parsed=extractSgrMouseEvents(input);assert.deepEqual(parsed.events,[{button:0,x:94,y:6,kind:'M'},{button:32,x:94,y:9,kind:'M'},{button:0,x:94,y:11,kind:'m'}]);assert.equal(parsed.remainder,'');const split=extractSgrMouseEvents('\x1b[<0;94;6M\x1b[<32;94');assert.equal(split.events.length,1);assert.equal(split.remainder,'\x1b[<32;94');});

test('showcase reel randomizes catalog order, boosts rare visuals, and preserves the server winner',()=>{const entries=['bust','common','rare','epic','legendary','mythic'].map((tier,index)=>({tier,model:tier+index}));let seed=7;const random=()=>((seed=(seed*48271)%2147483647)-1)/2147483646;assert.notDeepEqual(shuffleModels(entries,random).map(entry=>entry.model),entries.map(entry=>entry.model));const winner=entries[1],{reel,landing}=buildShowcaseReel(entries,winner,{length:10000,landing:9997,random});assert.equal(reel[landing],winner);assert.ok(showcaseWeight(reel[landing-1])>=showcaseWeight(entries[3]));const counts=Object.fromEntries(entries.map(entry=>[entry.tier,reel.filter(item=>item.tier===entry.tier).length]));assert.ok(counts.mythic>counts.bust*3);});

test('CLI status, collection, roll and disconnected wallet work without a browser surface',async t=>{const s=await server(t),key=await s.login(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootlm-cli-live-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,'config.json'),JSON.stringify({key,url:s.url}),{mode:0o600});const run=args=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,['src/cli.js',...args],{cwd:path.resolve('.'),env:{...process.env,LOOTLM_CONFIG_DIR:dir,NO_COLOR:'1'}});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);child.on('error',reject);child.on('close',code=>resolve({code,stdout,stderr}));});const status=await run(['status','--json']);assert.equal(status.code,0);assert.equal(JSON.parse(status.stdout).info.user.email,'one@test.local');const roll=await run(['roll','--json']);assert.equal(roll.code,0);const award=JSON.parse(roll.stdout).award;assert.match(award.id,/^award_/);const visible=await run(['status']);assert.equal(visible.code,0);assert.match(visible.stdout,/TOKENS/);assert.match(visible.stdout,/BUST|COMMON|RARE|EPIC|LEGENDARY|MYTHIC/);const collection=await run(['collection']);assert.equal(collection.code,0);assert.match(collection.stdout,/DISCOVERY 01/);assert.match(collection.stdout,/24 MODEL CARDS/);assert.match(collection.stdout,/TIER/);const wallet=await run(['wallet']);assert.equal(wallet.code,0);assert.match(wallet.stdout,/WALLET NOT CONNECTED/);assert.doesNotMatch(wallet.stdout,/http:\/\//);});

test('official OpenAI SDK supports text, streaming and tool calls',async t=>{
 const {default:OpenAI}=await import('openai');const s=await server(t);const key=await s.login();const user=s.store.authenticate(key),award=s.store.spin(user,'sdk',()=>10).award;
 const client=new OpenAI({apiKey:key,baseURL:s.url+'/v1',maxRetries:0});
 const body={model:award.id,messages:[{role:'user',content:'Hello SDK'}],max_tokens:128};
 const reply=await client.chat.completions.create(body);assert.match(reply.choices[0].message.content,/demo/);
 const stream=await client.chat.completions.create({...body,stream:true});let text='',usage;
 for await(const event of stream){text+=event.choices[0]?.delta?.content||'';if(event.usage)usage=event.usage;}
 assert.match(text,/Hello SDK/);assert.ok(usage.total_tokens>0);
 const tool=await client.chat.completions.create({...body,tools:[{type:'function',function:{name:'lookup',parameters:{type:'object',properties:{}}}}],tool_choice:'required'});
 assert.equal(tool.choices[0].message.tool_calls[0].function.name,'lookup');
});
