import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {Store,hash} from '../src/store.js';
import {createApp} from '../src/server.js';
import {normalizeUsage,DemoProvider} from '../src/providers.js';
const configuration=()=>({dataDir:':memory:',provider:'demo',accessCode:'test-secret',testers:['one@test.local','two@test.local'],admins:['one@test.local'],origin:'http://localhost:3131',secureCookie:false,liveEnabled:false,dailyUsd:5,maxOutput:1024,maxInputBytes:24000});
function setup(overrides={}){const cfg={...configuration(),...overrides};return {cfg,store:new Store(':memory:',cfg)};}
async function server(t,options={}){const {cfg,store}=setup(options.cfg);const {app,reconcile}=createApp(cfg,{store,provider:options.provider});const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));const url=`http://127.0.0.1:${s.address().port}`;t.after(()=>{s.closeAllConnections();s.close();store.close();});const call=async(route,body,key,extra={})=>{const r=await fetch(url+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(key?{Authorization:`Bearer ${key}`}:{ }),...extra.headers},body:body?JSON.stringify(body):undefined,...extra});let data;try{data=await r.json();}catch{}return {status:r.status,data,headers:r.headers};};const login=async(email='one@test.local')=>(await call('/auth/login',{email,code:'test-secret',cli:true})).data.key;return {cfg,store,url,call,login,reconcile};}

test('roll weights have exact boundaries, immutable snapshots, and replay safety',()=>{const {store}=setup();const u=store.user('one@test.local');const a=store.spin(u,'one',()=>0);assert.equal(a.award.choice.tier,'bust');assert.equal(a.award.total,1000000);assert.equal(store.spin(u,'one',()=>99).award.id,a.award.id);assert.equal(store.awards(u).length,1);assert.equal(store.spin(u,'two',()=>10).award.choice.tier,'common');assert.equal(store.spin(u,'three',()=>75).award.choice.tier,'strong');assert.equal(store.spin(u,'four',()=>95).award.choice.tier,'rare');const pool=store.pool();const changed=pool.entries.map(e=>({...e,name:e.name+' v2'}));store.publishPool(changed,u.id);assert.equal(store.award(u,a.award.id).choice.name,'Pocket Brain');assert.notEqual(store.pool().version,a.award.pool_version);store.close();});

test('reservations prevent overspending and settlement is exactly once',()=>{const {store}=setup();const u=store.user('a');const a=store.spin(u,'spin',()=>10).award;const r=store.reserve(u,a.id,'first','fp',800000,0).request;assert.throws(()=>store.reserve(u,a.id,'second','fp2',300000,0),e=>e.code==='insufficient_tokens');assert.equal(store.award(u,a.id).reserved,800000);store.settle(r.id,{input:100,output:200,cost:0});store.settle(r.id,{input:100,output:200,cost:0});assert.equal(store.award(u,a.id).remaining,999700);assert.equal(store.award(u,a.id).reserved,0);assert.equal(store.reserve(u,a.id,'first','fp',800000,0).prior.id,r.id);assert.throws(()=>store.reserve(u,a.id,'first','different',1,0),e=>e.code==='idempotency_conflict');store.close();});

test('user isolation, key hashing and revocation',()=>{const {store}=setup();const u=store.user('a'),v=store.user('b');const a=store.spin(u,'spin',()=>10).award;assert.throws(()=>store.award(v,a.id),e=>e.status===404);const k=store.credential(u);assert.equal(store.authenticate(k.key).id,u.id);assert.equal(store.db.prepare('SELECT hash FROM credentials WHERE id=?').get(k.id).hash,hash(k.key));assert.equal(store.keys(v).length,0);assert.equal(store.revoke(v,k.id),0);store.revoke(u,k.id);assert.equal(store.authenticate(k.key),null);store.close();});

test('daily cap includes active reservations; rejection releases once',()=>{const {store}=setup({dailyUsd:1});const u=store.user('a');const a=store.spin(u,'spin',()=>10).award;const r=store.reserve(u,a.id,'r','fp',100,.8).request;assert.throws(()=>store.reserve(u,a.id,'s','fp2',100,.3),e=>e.code==='daily_budget');store.release(r.id,'rejected');store.release(r.id,'rejected');assert.equal(store.award(u,a.id).reserved,0);assert.ok(store.reserve(u,a.id,'s','fp2',100,.9).request);store.close();});

test('uncertain requests remain reserved after recovery; unexpected costs pause inference',()=>{const {store}=setup();const u=store.user('a');const a=store.spin(u,'s',()=>10).award;const r=store.reserve(u,a.id,'r','f',100,.01).request;store.recover();assert.equal(store.request(r.id).status,'pending');assert.equal(store.award(u,a.id).reserved,100);store.settle(r.id,{input:80,output:30,cost:.02});assert.equal(store.setting('inferenceEnabled'),'false');assert.equal(store.award(u,a.id).remaining,999890);assert.equal(store.stats().audit[0].action,'reservation.exceeded');store.close();});

test('usage does not double count cached or reasoning tokens',()=>{assert.deepEqual(normalizeUsage({prompt_tokens:100,completion_tokens:60,prompt_tokens_details:{cached_tokens:90},completion_tokens_details:{reasoning_tokens:40},cost:.02},{inputPrice:1,outputPrice:2}),{input:100,output:60,cost:.02});assert.throws(()=>normalizeUsage({prompt_tokens:null,completion_tokens:1},{}));});

test('API authentication, CSRF, session cookie and admin isolation',async t=>{const s=await server(t);assert.equal((await s.call('/v1/models')).status,401);assert.equal((await s.call('/auth/login',{email:'not@test.local',code:'test-secret'})).status,401);const login=await s.call('/auth/login',{email:'one@test.local',code:'test-secret'});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.equal((await s.call('/internal/me',null,null,{headers:{Cookie:cookie.split(';')[0]}})).status,200);const key=await s.login();const csrf=await fetch(s.url+'/internal/spins',{method:'POST',headers:{Authorization:`Bearer ${key}`,Origin:'https://evil.example','Content-Type':'application/json','Idempotency-Key':'x'},body:'{}'});assert.equal(csrf.status,403);const second=await s.login('two@test.local');assert.equal((await s.call('/internal/admin',null,second)).status,403);});

test('end-to-end roll, chat, streaming, tools and balance',async t=>{const s=await server(t);const key=await s.login();let spin=await fetch(s.url+'/internal/spins',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':'s'},body:'{}'});assert.equal(spin.status,200);const {award}=await spin.json();const body={model:award.id,messages:[{role:'user',content:'hello'}],max_tokens:128};const chat=await s.call('/v1/chat/completions',body,key);assert.equal(chat.status,200);assert.equal(chat.data.model,award.id);assert.match(chat.data.choices[0].message.content,/demo/);const spent=chat.data.usage.total_tokens;assert.equal((await s.call('/v1/allowances',null,key)).data.data[0].remaining,1000000-spent);
 const stream=await fetch(s.url+'/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({...body,stream:true})});assert.equal(stream.status,200);assert.match(stream.headers.get('content-type'),/event-stream/);const text=await stream.text();assert.match(text,/data: \[DONE\]/);assert.match(text,/prompt_tokens/);
 const tools=await s.call('/v1/chat/completions',{...body,tools:[{type:'function',function:{name:'weather',parameters:{type:'object',properties:{}}}}],tool_choice:'required'},key);assert.equal(tools.status,200);assert.equal(tools.data.choices[0].message.tool_calls[0].function.name,'weather');assert.equal((await s.call('/v1/usage',null,key)).data.data.length,3);
 const k2=await s.login('two@test.local');assert.equal((await s.call('/v1/chat/completions',body,k2)).status,404);
});

test('inference idempotency rejects repeats without a second provider call',async t=>{const s=await server(t);const key=await s.login();const u=s.store.authenticate(key),a=s.store.spin(u,'s',()=>10).award;const body={model:a.id,messages:[{role:'user',content:'hello'}],max_tokens:20};const invoke=()=>fetch(s.url+'/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':'same'},body:JSON.stringify(body)});assert.equal((await invoke()).status,200);assert.equal((await invoke()).status,409);assert.equal(s.store.usage(u).length,1);});

test('unsupported parameters, context bounds and output limits fail before reservation',async t=>{const s=await server(t);const k=await s.login();const u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;const b={model:a.id,messages:[{role:'user',content:'hello'}],max_tokens:10};for(const body of [{...b,response_format:{}},{...b,max_tokens:2000},{...b,messages:[{role:'user',content:'x'.repeat(25000)}]},{...b,messages:[{role:'user',content:[{type:'image_url'}]}]}])assert.equal((await s.call('/v1/chat/completions',body,k)).status,400);assert.equal(s.store.usage(u).length,0);});

test('in-flight concurrent calls cannot exceed per-user limit',async t=>{let unblock;const gate=new Promise(r=>unblock=r);const demo=new DemoProvider();const provider={async generate(...args){await gate;return demo.generate(...args);},async reconcile(){return null;}};const s=await server(t,{provider});const k=await s.login(),u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;const b={model:a.id,messages:[{role:'user',content:'hi'}],max_tokens:10};const calls=[s.call('/v1/chat/completions',b,k),s.call('/v1/chat/completions',b,k)];for(let i=0;i<100&&s.store.usage(u).length<2;i++)await new Promise(r=>setTimeout(r,5));const third=await s.call('/v1/chat/completions',b,k);assert.equal(third.status,429);unblock();for(const result of await Promise.all(calls))assert.equal(result.status,200);assert.equal(s.store.award(u,a.id).reserved,0);});

test('transport failure retains reservation and reconciliation settles exactly once',async t=>{const provider={async generate(_b,_c,{onId}){onId('generation_test');throw Error('Connection lost');},async reconcile(){return {input:12,output:9,cost:0};}};const s=await server(t,{provider});const k=await s.login(),u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;const r=await s.call('/v1/chat/completions',{model:a.id,messages:[{role:'user',content:'hi'}],max_tokens:20},k);assert.equal(r.status,502);assert.ok(s.store.award(u,a.id).reserved>0);assert.equal(s.store.usage(u)[0].status,'pending');await s.reconcile();await s.reconcile();assert.equal(s.store.award(u,a.id).reserved,0);assert.equal(s.store.award(u,a.id).remaining,999979);});

test('live provider is blocked without explicit enablement',async t=>{const s=await server(t,{cfg:{provider:'openrouter'},provider:{generate(){throw Error('must not call');}}});const k=await s.login(),u=s.store.authenticate(k),a=s.store.spin(u,'s',()=>10).award;assert.equal((await s.call('/v1/chat/completions',{model:a.id,messages:[{role:'user',content:'hi'}]},k)).status,503);assert.equal(s.store.usage(u).length,0);});

test('SQLite data survives reopening',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootlm-'));try{const cfg=configuration(),file=path.join(dir,'db.sqlite');let store=new Store(file,cfg);const u=store.user('a'),a=store.spin(u,'s',()=>10).award;store.close();store=new Store(file,cfg);assert.equal(store.award(u,a.id).remaining,1000000);assert.equal(store.spin(u,'s').award.id,a.id);store.close();}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('CLI help and safe config output',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootlm-cli-'));try{const env={...process.env,LOOTLM_CONFIG_DIR:dir};const result=spawnSync(process.execPath,['src/cli.js','help'],{encoding:'utf8',env});assert.equal(result.status,0);assert.match(result.stdout,/lootlm roll/);fs.writeFileSync(path.join(dir,'config.json'),JSON.stringify({key:'secret-value',url:'http://localhost:3131'}));const conf=spawnSync(process.execPath,['src/cli.js','config'],{encoding:'utf8',env});assert.equal(conf.status,0);assert.doesNotMatch(conf.stdout,/secret-value/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('official OpenAI SDK supports text, streaming and tool calls',async t=>{
 const {default:OpenAI}=await import('openai');const s=await server(t);const key=await s.login();const user=s.store.authenticate(key),award=s.store.spin(user,'sdk',()=>10).award;
 const client=new OpenAI({apiKey:key,baseURL:s.url+'/v1',maxRetries:0});
 const body={model:award.id,messages:[{role:'user',content:'Hello SDK'}],max_tokens:128};
 const reply=await client.chat.completions.create(body);assert.match(reply.choices[0].message.content,/demo/);
 const stream=await client.chat.completions.create({...body,stream:true});let text='',usage;
 for await(const event of stream){text+=event.choices[0]?.delta?.content||'';if(event.usage)usage=event.usage;}
 assert.match(text,/Hello SDK/);assert.ok(usage.total_tokens>0);
 const tool=await client.chat.completions.create({...body,tools:[{type:'function',function:{name:'lookup',parameters:{type:'object',properties:{}}}}],tool_choice:'required'});
 assert.equal(tool.choices[0].message.tool_calls[0].function.name,'lookup');
});
